     module error_description_module
     type error_description
         integer id
         character*255 description
     end type error_description
 
        type(error_description), parameter :: errors_desciptions(  202  ) = (/ &
               error_description(   -1111, '	MIX: Wrong input(s) to a routine. These are internal errors, for example negative temperatures, wrong iFlash values etc. are caught                                                                                                                           '), &
               error_description(   -1234, '	PURE: PhaseDet, p(rho_it,T_it)  -->  press_input                                                                                                                                                                                                              '), &
               error_description(   -1235, '	PURE: Temperature iteration T(p,h) failed                                                                                                                                                                                                                     '), &
               error_description(   -1444, '	Function Fug_DryIce: FUGCOPURE_CALC: Exponent > 700. Argument to exponential function too big in dry ice fugacity calculation                                                                                                                                 '), &
               error_description(   -2111, '	PHASEDET: Subroutine RachRiche error during generation of startvalues                                                                                                                                                                                         '), &
               error_description(   -2211, '	Subroutine PHASEDET_PURE: Flash calculation did not converge                                                                                                                                                                                                  '), &
               error_description(   -2212, '	Subroutine MAXWELL: Flash calculation with MAXWELL did not converge                                                                                                                                                                                           '), &
               error_description(   -2222, '	FLASH: Flash calculation did not converge                                                                                                                                                                                                                     '), &
               error_description(   -2223, '	Function TSUB_EQ: SUBLIMATION TEMPERATURE iteration did not converge (ancillary equation)                                                                                                                                                                     '), &
               error_description(   -2224, '	PHASEDET_SOL: MELTING TEMPERATURE iteration did not converge (ancillary equation)                                                                                                                                                                             '), &
               error_description(   -2225, '	PHASEDET_SOL: SUBLIMATION PRESSURE calculation failed                                                                                                                                                                                                         '), &
               error_description(   -2226, '	PHASEDET_SOL: MELTING PRESSURE calculation failed                                                                                                                                                                                                             '), &
               error_description(   -2230, '	PHASEDET_SOL: MELTING LINE: Given pressure not valid                                                                                                                                                                                                          '), &
               error_description(   -2231, '	PHASEDET_SOL: MELTING LINE: Given temperature not valid                                                                                                                                                                                                       '), &
               error_description(   -2232, '	PHASEDET_SOL: SUBLIMATION LINE: Given pressure not valid                                                                                                                                                                                                      '), &
               error_description(   -2233, '	PHASEDET_SOL: SUBLIMATION LINE: Given temperature not valid                                                                                                                                                                                                   '), &
               error_description(   -2408, '	Internal Error in Flash_Pure_PhaseBoundary (found same density roots)                                                                                                                                                                                         '), &
               error_description(   -2908, '	cubic, LKP or generalized equation: No cp0 parameters set                                                                                                                                                                                                     '), &
               error_description(   -3333, '	MIX: Step size reduction error in flash algorithm (step size becomes too small)                                                                                                                                                                               '), &
               error_description(   -4321, '	MIX: Flash algorithm converged to unreasonable temperatures                                                                                                                                                                                                   '), &
               error_description(   -4322, '	Subroutine FLASH_PHASEBOUNDARY_CALC: MIX flash algorithm converged to unreasonable pressures                                                                                                                                                                  '), &
               error_description(   -4323, '	MIX: Flash algorithm converged to two phases with the same compositions                                                                                                                                                                                       '), &
               error_description(   -4401, '	Subroutine FLASH_PHASEBOUNDARY: MIX p,x(liq)-flash failed: no bubble point found                                                                                                                                                                              '), &
               error_description(   -4402, '	Subroutine FLASH_PHASEBOUNDARY: MIX p,x(vap)-flash failed: no dew point found                                                                                                                                                                                 '), &
               error_description(   -4403, '	Subroutine FLASH_PHASEBOUNDARY: MIX t,x(liq)-flash failed: no bubble point found                                                                                                                                                                              '), &
               error_description(   -4404, '	Subroutine FLASH_PHASEBOUNDARY: MIX t,x(vap)-flash failed: no dew point found                                                                                                                                                                                 '), &
               error_description(   -4405, '	MIX: ph-flash internal error                                                                                                                                                                                                                                  '), &
               error_description(   -4406, '	Subroutine PHASEDET_PS: MIX ps-flash internal error                                                                                                                                                                                                           '), &
               error_description(   -4407, '	MIX: td-flash internal error                                                                                                                                                                                                                                  '), &
               error_description(   -4408, '	CRITICAL POINT FOR MIXTURES: internal error                                                                                                                                                                                                                   '), &
               error_description(   -4409, '	Calculation of Henry constant not possible because temperature is lower than triple point temperature or higher than critical temperature                                                                                                                     '), &
               error_description(   -4444, '	MIX: LUDECOMP failed to invert matrix                                                                                                                                                                                                                         '), &
               error_description(   -5211, '	Surface tension not implemented for mixtures                                                                                                                                                                                                                  '), &
               error_description(   -5222, '	Surface tension not defined in the homogeneous region                                                                                                                                                                                                         '), &
               error_description(   -5223, '	Property for mixtures not implemented                                                                                                                                                                                                                         '), &
               error_description(   -5234, '	No model for this property and fluid available                                                                                                                                                                                                                '), &
               error_description(   -5235, '	Dielectric constant models cannot be mixed with model DE2                                                                                                                                                                                                     '), &
               error_description(   -5242, '	Error in viscosity calculation                                                                                                                                                                                                                                '), &
               error_description(   -5243, '	Existing model for the viscosity not implemented yet                                                                                                                                                                                                          '), &
               error_description(   -5244, '	Existing model for the thermal conductivity not implemented yet                                                                                                                                                                                               '), &
               error_description(   -5245, '	No viscosity model exists, which is needed for the calculation of the critical enhancement of the thermal conductivity                                                                                                                                        '), &
               error_description(   -5246, '   VS7 model is treated as VS9 model. Rename it to VS7 and adjust the format in the FLD file.                                                                                                                                                                  '), &
               error_description(   -5247, '   Literature reference only available for pure fluids and binary mixtures                                                                                                                                                                                     '), &
               error_description(   -5248, '	Property only available for mixtures                                                                                                                                                                                                                          '), &
               error_description(   -5249, '	Property only available for binary mixtures                                                                                                                                                                                                                   '), &
               error_description(   -5250, '	Quality not implemented as input parameter for mixtures                                                                                                                                                                                                       '), &
               error_description(   -5251, '	This diagram is not defined for the specified number of fluids                                                                                                                                                                                                '), &
               error_description(   -5300, '	ECS: invalid reference fluid                                                                                                                                                                                                                                  '), &
               error_description(   -5301, '	ECS: internal error                                                                                                                                                                                                                                           '), &
               error_description(   -5302, '	ECS: iteration failed                                                                                                                                                                                                                                         '), &
               error_description(   -5400, '	Internal error while iterating the melting temperature                                                                                                                                                                                                        '), &
               error_description(   -5501, '	Creation of four points at low pressures failed: generation of starting point failed. Stability analysis failed.                                                                                                                                              '), &
               error_description(   -5502, '	Phase envelope: generation of start values failed                                                                                                                                                                                                             '), &
               error_description(   -5503, '	Phase envelope: generation of start values failed                                                                                                                                                                                                             '), &
               error_description(   -5507, '	Subroutine PHASENV: MIX: phase envelope calculation failed (step reduction becomes too large)                                                                                                                                                                 '), &
               error_description(   -5508, '	Subroutine PHASENV: MIX: phase envelope calculation failed                                                                                                                                                                                                    '), &
               error_description(   -5509, '	Subroutine PHASENV_pbased or PHASENV_vbased: MIX: phase envelope calculation failed                                                                                                                                                                           '), &
               error_description(   -5511, '	p_min for "normal" phase env. OR p_max for open phase env. reached OR exit if the specified point is found and the routine is called from the phase boundary flash algorithm OR one of these variables does not change any more: T, p, rho_vap                '), &
               error_description(   -5520, '	Subroutine PHASENV: MIX: too many points found -> exceeds the vector storage capacity                                                                                                                                                                         '), &
               error_description(   -5530, '	Subroutine pxdiag: T is larger than tc(1) and tc(2)                                                                                                                                                                                                           '), &
               error_description(   -5531, '	Subroutine ptxdiag_out: prop is below 0.5*min(tminfluid) or 0.5*min(pminfluid) respectively                                                                                                                                                                   '), &
               error_description(   -5555, '	Subroutine SATPLOT: MIX: Phase envelope calculation failed                                                                                                                                                                                                    '), &
               error_description(   -5566, '	Subroutine SYSOFFEQS_PT: MIX: Internal error in pt-flash                                                                                                                                                                                                      '), &
               error_description(   -5660, '	Density maximum not implemented for mixtures or wrong input code (only TP valid)                                                                                                                                                                              '), &
               error_description(   -5661, '	Iteration of density maximum failed                                                                                                                                                                                                                           '), &
               error_description(   -5662, '   Iteration of temperature failed                                                                                                                                                                                                                             '), &
               error_description(   -5666, '	Function DSPIN_EOS: Spinodals: No valid input code, only TLIQ and TVAP possible                                                                                                                                                                               '), &
               error_description(   -5667, '	Function DSPIN_CALC: Spinodals: Change in curvature between minimum and phase boundary (unreasonable result)                                                                                                                                                  '), &
               error_description(   -5668, '	Function DSPIN_EOS: Spinodales not implemented for mixtures                                                                                                                                                                                                   '), &
               error_description(   -5669, '	Function DSPIN_EOS: Error when calculating the density of the spinodal                                                                                                                                                                                        '), &
               error_description(   -5700, '	Function PROP_EOS: Valid input combination for PNUMER_EOS is "TD" only                                                                                                                                                                                        '), &
               error_description(   -5777, '	Costald EOS: Different EOS types cannot be combined here                                                                                                                                                                                                      '), &
               error_description(   -5778, '	Function PROP_EOS: Costald EOS: No valid input code, only TLIQ or TP possible or wrong property (only density possible)                                                                                                                                       '), &
               error_description(   -5888, '	Function VSATTAIT: Costald EOS: Temperature out of valid temperature range                                                                                                                                                                                    '), &
               error_description(   -5997, '	Function PROP_EOS: RKM EOS: No valid input code, only TLIQ possible or wrong property (only density possible)                                                                                                                                                 '), &
               error_description(   -5998, '	Function PROP_EOS: ERKM EOS: No valid input code, only TLIQ or TP possible or wrong property (only density possible)                                                                                                                                          '), &
               error_description(   -5999, '	Function v_RKM: Revised Klosek-McKinley EOS: Temperature and or pressure out of valid range                                                                                                                                                                   '), &
               error_description(   -6000, '	Subroutine REF_CALC: No reference state set                                                                                                                                                                                                                   '), &
               error_description(   -6001, '	Acentric factor for generalized negative => calculation not possible                                                                                                                                                                                          '), &
               error_description(   -6600, '	No strict equation boundaries available                                                                                                                                                                                                                       '), &
               error_description(   -6666, '	Property in two-phase region undefined                                                                                                                                                                                                                        '), &
               error_description(   -6667, '	Property in homogeneous region undefined                                                                                                                                                                                                                      '), &
               error_description(   -7000, '	UNCERTAINTIES: Estimation of uncertainties only possible for pure fluids                                                                                                                                                                                      '), &
               error_description(   -7001, '	UNCERTAINTIES: Uncty File not found                                                                                                                                                                                                                           '), &
               error_description(   -7002, '	UNCERTAINTIES: Estimation of uncertainties only possible for Helmholtz EOS (see uncty file)                                                                                                                                                                   '), &
               error_description(   -7003, '	UNCERTAINTIES: estimation in 2phase region not yet implemented                                                                                                                                                                                                '), &
               error_description(   -7777, '	MIX: Calculation of vapor fugacities failed                                                                                                                                                                                                                   '), &
               error_description(   -7778, '	MIX: Calculation of liquid fugacities failed                                                                                                                                                                                                                  '), &
               error_description(   -7779, '	MIX: Calculation of solid fugacities failed                                                                                                                                                                                                                   '), &
               error_description(   -7877, '	DLL could not be opened in Excel                                                                                                                                                                                                                              '), &
               error_description(   -7878, '	SETUP: Fluid name or path wrong                                                                                                                                                                                                                               '), &
               error_description(   -7879, '	SETUP Error: Opening fluid file, does not exist in CAS list                                                                                                                                                                                                   '), &
               error_description(   -7880, '	SETUP Error: End of fluid-file is reached during read                                                                                                                                                                                                         '), &
               error_description(   -7881, '	SETUP Error: Opening .MIX file                                                                                                                                                                                                                                '), &
               error_description(   -7882, '	SETUP Error: End of .MIX-file is reached during read                                                                                                                                                                                                          '), &
               error_description(   -7883, '	SETUP Error: Opening atcoeff file                                                                                                                                                                                                                             '), &
               error_description(   -7884, '	SETUP Error: CAS list was not found                                                                                                                                                                                                                           '), &
               error_description(   -7885, '	SETUP Error: Opening SRK file                                                                                                                                                                                                                                 '), &
               error_description(   -7886, '	SETUP Error: Opening PR file                                                                                                                                                                                                                                  '), &
               error_description(   -7887, '	SETUP Error: Opening LKP file                                                                                                                                                                                                                                 '), &
               error_description(   -7888, '	SETUP Error: Opening BIN SRK or PR file                                                                                                                                                                                                                       '), &
               error_description(   -7889, '	SETUP Error: Opening BIN LKP file                                                                                                                                                                                                                             '), &
               error_description(   -7890, '	SETUP Error: CAS-ID not found                                                                                                                                                                                                                                 '), &
               error_description(   -7891, '	SETUP Error: Opening COSTALD file                                                                                                                                                                                                                             '), &
               error_description(   -7892, '	SETUP Error: Only Helmholtz EOS, PR, SRK, LKP and the corresponding mixing rules are hardcoded at the moment                                                                                                                                                  '), &
               error_description(   -7893, '	SETUP Error: Opening RKM files                                                                                                                                                                                                                                '), &
               error_description(   -7894, '	SETUP Error: Read error in srkfluids.fld                                                                                                                                                                                                                      '), &
               error_description(   -7895, '	SETUP Error: Read error in bin_srk.mix or bin_pr.mix                                                                                                                                                                                                          '), &
               error_description(   -7896, '	SETUP Error: Read error in rk_qk.par                                                                                                                                                                                                                          '), &
               error_description(   -7897, '	SETUP Error: Read error in Interac.par                                                                                                                                                                                                                        '), &
               error_description(   -7898, '	SETUP Error: COSMO-SAC                                                                                                                                                                                                                                        '), &
               error_description(   -7899, '	COSMO-SAC_CALC Error                                                                                                                                                                                                                                          '), &
               error_description(   -7999, '	Wrong equation format (e.g. ECS)                                                                                                                                                                                                                              '), &
               error_description(   -8000, '	Internal error Helmholtz_reader (sub_part found twice)                                                                                                                                                                                                        '), &
               error_description(   -8001, '	Internal error: Read error in Costald.fld                                                                                                                                                                                                                     '), &
               error_description(   -8002, '	RM: Fluid components do not match the 8 possible components of the RKM                                                                                                                                                                                        '), &
               error_description(   -8877, '	PURE: Density iteration failed                                                                                                                                                                                                                                '), &
               error_description(   -8878, '	Fluid not found                                                                                                                                                                                                                                               '), &
               error_description(   -8879, '	gE-Model: Fluid or file not found                                                                                                                                                                                                                             '), &
               error_description(   -8880, '	Costald fluid not found                                                                                                                                                                                                                                       '), &
               error_description(   -8881, '	Costald parameter file not found                                                                                                                                                                                                                              '), &
               error_description(   -8888, '	Density iteration failed                                                                                                                                                                                                                                      '), &
               error_description(   -8889, '	find_crit_tpd: iteration of critical point failed                                                                                                                                                                                                             '), &
               error_description(   -9000, '	SETUP Error: Parameter file for generalized EOS not found                                                                                                                                                                                                     '), &
               error_description(   -9876, '	NAN in FNRDERIVSMIX - fugcoef_pure, SRK, dlog( <0)                                                                                                                                                                                                            '), &
               error_description(   -9901, '	Calculation not possible for pure fluids                                                                                                                                                                                                                      '), &
               error_description(   -9902, '	Calculation not possible for mixtures                                                                                                                                                                                                                         '), &
               error_description(   -9903, '	Calculation not possible for pure substances or binary mixtures                                                                                                                                                                                               '), &
               error_description(   -9904, '	Calculation not possible for solid phase of chosen substance                                                                                                                                                                                                  '), &
               error_description(   -9907, '	Pressure <= lower pressure limit of the corresponding equation                                                                                                                                                                                                '), &
               error_description(   -9908, '	Pressure >= lower pressure limit of the corresponding equation                                                                                                                                                                                                '), &
               error_description(   -9909, '	Temperature <= lower temperature limit of the corresponding equation                                                                                                                                                                                          '), &
               error_description(   -9910, '	Temperature >= upper temperature limit of the corresponding equation                                                                                                                                                                                          '), &
               error_description(   -9911, '	Temperature input <= 0                                                                                                                                                                                                                                        '), &
               error_description(   -9912, '	Temperature <= Tminfluid                                                                                                                                                                                                                                      '), &
               error_description(   -9913, '	Temperature >= Tmaxfluid                                                                                                                                                                                                                                      '), &
               error_description(   -9914, '	Density >= Rhomaxfluid                                                                                                                                                                                                                                        '), &
               error_description(   -9915, '	p >= pmelt --> solid phase                                                                                                                                                                                                                                    '), &
               error_description(   -9916, '	Input parameters out of range (viscosity of water)                                                                                                                                                                                                            '), &
               error_description(   -9917, '	ALLPROP_HOM: phase_ind out of range (phase_ind is an input parameter that specifies the phase which is tried)                                                                                                                                                 '), &
               error_description(   -9918, '	Temperature <= Tmin of transport equations                                                                                                                                                                                                                    '), &
               error_description(   -9919, '	Temperature >= Tmax of transport equations                                                                                                                                                                                                                    '), &
               error_description(   -9920, '	Density >= rhomax of transport equations                                                                                                                                                                                                                      '), &
               error_description(   -9922, '	Density input <= 0                                                                                                                                                                                                                                            '), &
               error_description(   -9932, '	Pressure input >=  Pmaxfluid                                                                                                                                                                                                                                  '), &
               error_description(   -9933, '	Pressure input <= 0                                                                                                                                                                                                                                           '), &
               error_description(   -9935, '	Property not available                                                                                                                                                                                                                                        '), &
               error_description(   -9936, '	Input Property out of range (seawater or brines); see manual for range of validity                                                                                                                                                                            '), &
               error_description(   -9942, '	Entropy input out of range                                                                                                                                                                                                                                    '), &
               error_description(   -9941, '	Enthalpy input out of range                                                                                                                                                                                                                                   '), &
               error_description(   -9943, '	T rho flash, density cannot be found in the given range of pmin to pmax                                                                                                                                                                                       '), &
               error_description(   -9950, '	Error in composition convertion                                                                                                                                                                                                                               '), &
               error_description(   -9951, '	One mole fraction exceeds 0 < x < 1                                                                                                                                                                                                                           '), &
               error_description(   -9952, '	Sum of the mole fractions is not 1                                                                                                                                                                                                                            '), &
               error_description(   -9953, '	Number of fluids =/ number of mole fractions =/ number of eqtypes                                                                                                                                                                                             '), &
               error_description(   -9954, '	Error in composition entry                                                                                                                                                                                                                                    '), &
               error_description(   -9955, '	Wrong Input (combination)                                                                                                                                                                                                                                     '), &
               error_description(   -9956, '	AGA8: Wrong Input, only TD is valid                                                                                                                                                                                                                           '), &
               error_description(   -9957, '	EOS_Indicator does not exist or wrong mixtype                                                                                                                                                                                                                 '), &
               error_description(   -9958, '	Cubic EOS cannot be mixed with Helmholtz EOS                                                                                                                                                                                                                  '), &
               error_description(   -9959, '	Error in EOS_Indicator entry, wrong format                                                                                                                                                                                                                    '), &
               error_description(   -9960, '	Error in fluid entry (e.g. fluidname contains blanks)                                                                                                                                                                                                         '), &
               error_description(   -9961, '	Option only valid for Helmholtz, PR, SRK, and LKP                                                                                                                                                                                                             '), &
               error_description(   -9971, '	Negative radical in calculation of speed of sound                                                                                                                                                                                                             '), &
               error_description(   -9981, '	Call of Flash_pure with Temp <= ttp or Temp >= tc                                                                                                                                                                                                             '), &
               error_description(   -9982, '	Call of Flash_pure with press <= ptp or press >= pc                                                                                                                                                                                                           '), &
               error_description(   -9994, '	AGA8: Only valid in gas phase                                                                                                                                                                                                                                 '), &
               error_description(   -9995, '	AGA8: A fnr-function is needed for the calculation, which is not provided by the AGA8                                                                                                                                                                         '), &
               error_description(   -9996, '	AGA8: Fluid components do not match the 21 possible components of the AGA8                                                                                                                                                                                    '), &
               error_description(   -9997, '	AGA8: Density out of range (valid only up to 50% of critical density of mixture)                                                                                                                                                                              '), &
               error_description(   -9998, '	AGA8: Temperature out of range (valid between 143.15K and 453.15K)                                                                                                                                                                                            '), &
               error_description(   -9999, '	AGA8: Pressure out of range (valid up to 280MPa)                                                                                                                                                                                                              '), &
               error_description(  -12800, '  Property not implemented for seawater or brines                                                                                                                                                                                                              '), &
               error_description(  -12900, '	Property not provided / implemented for solid equation                                                                                                                                                                                                        '), &
               error_description(  -12901, '	Input combination not implemented for solids                                                                                                                                                                                                                  '), &
               error_description(  -12902, '	No solid model available for chosen substances                                                                                                                                                                                                                '), &
               error_description(  -12910, '  Input combination not implemented for seawater or brines                                                                                                                                                                                                     '), &
               error_description(  -14444, '	Wrong value in solidtype(1). Either internal error, or the solid former does not exist                                                                                                                                                                        '), &
               error_description(  -15566, '	Internal error in PhaseDet_sol                                                                                                                                                                                                                                '), &
               error_description(  -15567, '	Internal error in PhaseDet_ph_ps_sol                                                                                                                                                                                                                          '), &
               error_description(  -15570, '	Internal error in Flash_PhaseBoundary_sol                                                                                                                                                                                                                     '), &
               error_description(  -15571, '	Internal error in ptflash_sol_NC_4P                                                                                                                                                                                                                           '), &
               error_description(  -15572, '	Internal error in ptflash_sol_NC_2P                                                                                                                                                                                                                           '), &
               error_description(  -18867, '	Pressure iteration for solid failed                                                                                                                                                                                                                           '), &
               error_description(  -19900, '	Prediction of solids only possible in combination with Helmholtz EOS                                                                                                                                                                                          '), &
               error_description(  -19912, '	Temperature <= tmin of solid equation                                                                                                                                                                                                                         '), &
               error_description(  -19914, '	Density >= rhomax for solid                                                                                                                                                                                                                                   '), &
               error_description(  -19915, '	p >= pmelt -->  solid phase, no solid equation available or limits of solid equation exceeded                                                                                                                                                                 '), &
               error_description(  -19932, '	Pressure >= pmax for solid equation                                                                                                                                                                                                                           '), &
               error_description(  -19941, '	Enthalpy or entropy input out of range                                                                                                                                                                                                                        '), &
               error_description(  -44444, '	PURE: Density iteration failed (rho_calc)                                                                                                                                                                                                                     '), &
               error_description( -101010, '	Internal error in Phasedet_sol for mixtures                                                                                                                                                                                                                   '), &
               error_description( -111111, '	Solid function not activated                                                                                                                                                                                                                                  '), &
               error_description( -121212, '	Error while generating start values for VLE pure, press or Temp <= 0                                                                                                                                                                                          '), &
               error_description( -121213, '	Invalid iFlash entry in VLE pure                                                                                                                                                                                                                              '), &
               error_description( -123456, '	Error in molar specific handling (only "molar", "specific", or "reduced" allowed)                                                                                                                                                                             '), &
               error_description( -123457, '	Prop_unit subroutine: Invalid Property                                                                                                                                                                                                                        '), &
               error_description( -898964, '	Flash_Pure_PhaseBoundary_calc: Density iteration failed                                                                                                                                                                                                       '), &
               error_description( -898965, '	Flash_Pure_PhaseBoundary_calc did not converge in specified number of iterations                                                                                                                                                                              '), &
               error_description( -898966, '	Flash_Pure_PhaseBoundary_calc: safety caution for numerical effects (see oil, Pvap is 1.d-10 --> very small steps)                                                                                                                                            '), &
               error_description( -898967, '	Flash_Pure_PhaseBoundary_calc: wrong solution (wrong slope)                                                                                                                                                                                                   '), &
               error_description( -898968, '	Flash_Pure_PhaseBoundary_calc: pure fluid in two phase region, density cannot be determined                                                                                                                                                                   ')  &
        /)


    contains

    end module error_description_module


    subroutine TRANSLATE_ERRORS_STDCALL (error, errorcodes)
    !DEC$ ATTRIBUTES DLLEXPORT, decorate, alias : "TRANSLATE_ERRORS_STDCALL" :: TRANSLATE_ERRORS_STDCALL
    !DEC$ ATTRIBUTES stdcall, reference :: TRANSLATE_ERRORS_STDCALL
    implicit none



    !define input variables
    Integer, intent(in):: error
    !define output variables
    Character*255, intent(out):: errorcodes



    call TRANSLATE_ERRORS (error, errorcodes)

    end subroutine

 
    subroutine TRANSLATE_ERRORS(error, errorcodes)
    !DEC$ ATTRIBUTES DLLEXPORT :: TRANSLATE_ERRORS

    use error_description_module

    implicit none



    Integer, intent(in):: error
    Character*255, intent(out):: errorcodes
    Integer i
    
    do i=1,size(errors_desciptions)
        if (errors_desciptions(i).id == error) then
            errorcodes = errors_desciptions(i).description
            return
        endif
    enddo

    errorcodes = 'Error code not found!'

    end subroutine

 
  
   
    integer function IS_ERROR_STDCALL (error)
    !DEC$ ATTRIBUTES DLLEXPORT, decorate, alias : "IS_ERROR_STDCALL" :: IS_ERROR_STDCALL
    !DEC$ ATTRIBUTES stdcall, reference :: IS_ERROR_STDCALL
    implicit none



    !define input variables
    Integer, intent(in):: error
    !define output variables
    Integer IS_ERROR



    IS_ERROR_STDCALL = IS_ERROR(error)

    end function

 
    integer function IS_ERROR(error)
    !DEC$ ATTRIBUTES DLLEXPORT :: IS_ERROR

    use error_description_module

    implicit none

    Integer, intent(in):: error

    Integer i
    
    do i=1,size(errors_desciptions)
        if (errors_desciptions(i).id == error) then
            IS_ERROR = 1                    ! return 1, alternative: return error-number
            return
        endif
    enddo

    IS_ERROR = 0

    end function
